### ISSUE TITLE
Swapping

### ISSUE THREAD

**Issue by valarauca** [cesarb/clear_on_drop#1]
This library doesn't seem to handle if data is heap allocated, swapped to disk, and paged back in at a later time. A copy of that memory page will remain on disk.

**Comment by cesarb** [comment]
You're right, it doesn't. The ClearOnDrop struct is agnostic as to where the data is stored; it can be on the stack, on the normal heap, or on a `mlock`ed heap maintained by a separate crate.

Since the number of pages a process can `mlock` is often very low (something like 16 pages), the locked pages should be managed together as a heap, instead of locking random pages full of unrelated data in memory. I feel this task is better left to a dedicated crate.

In fact, I changed it from my original design (which allowed only `&mut T`) precisely to make it easier to integrate with such a crate, once one is written.

Therefore, I consider managing locked pages outside the scope of this crate.

**Comment by burdges** [comment]
There are several crates that do `mlock`ed heaps, but they'll all be deprecated or reworked once allocators land.  At least https://github.com/stouset/secrets can encrypt data in memory, which presumably allows more storage than `mlock` and handles hibernate better.
