### ISSUE TITLE
Support strings

### ISSUE THREAD

**Issue by vks** [cesarb/clear_on_drop#13]
Currently it seems impossible to have `ClearOnDrop<String>`. It should be save to set a string byte-wise to zero, because it still will be valid UTF-8.

**Comment by cesarb** [comment]
It's not safe to use `ClearOnDrop` with heap-allocated resizeable types like `Vec<T>` or `String` (which is actually `Vec<u8>`), since their contents move on the heap when resized, and the clearing mechanism can only clear their final location and size. You should instead use `Box<[T]>` or `Box<str>`, which have a fixed size and don't move on the heap.

That said, `InitializableFromZeroed` is currently not implemented for `str`. I'm not sure about its use case (`Box<str>` seems a bit unusual), but I might look into implementing it later (and making sure the documentation makes it clear that one should use `.into_boxed_slice()`/`.into_boxed_str()` as the place, instead of the `Vec` or `String` directly).

**Comment by vks** [comment]
By "safe" I ment memory safe, which I think it is. You are of course right about the secrecy, but if you don't push to the string there should be no problem. Of course it is nicer to have this enforced by the type system.

> I'm not sure about its use case (Box<str> seems a bit unusual)

Well, I want to have a secret string to generate a human-readable password, where something based on `str` makes more sense than `u8`, because it should be valid UTF-8. If you want to enforce secrecy with the type system, it seems like `Box<str>` is the only option for that use-case.

**Comment by burdges** [comment]
He does not mean memory safe.  He means `push` can trigger a reallocation, which fails to zero.  

You must customize `Vec` itself to do this zeroing on reallocation.  You could maybe modify the `arrayvec` crate so that `ArrayVec<Box<A>>` etc work too, but I'm not sure that's easier.

As an aside, I'd think a generated password should initially be `[u8]` because not everyone can type any given UTF-8 character.  If a user demonstrates that they can type a given UTF-8 character by doing so, then that password should be treated as valid, but that's not a generated password.

**Comment by vks** [comment]
> As an aside, I'd think a generated password should initially be [u8] because not everyone can type any given UTF-8 character.

I disagree. You will never generate a password by using random `u8`, because many ASCII characters are not printable. If you are using [Diceware](https://en.wikipedia.org/wiki/Diceware), you actually might want to use non-ASCII symbols for foreign languages, where UTF-8 is much more appropriate.

**Comment by cesarb** [comment]
Thinking more about it, `ClearOnDrop<String>` is actually safe, since the `String` is moved within the `ClearOnDrop`, and thus its size- and capacity-modifying methods aren't accessible anymore (same with `Vec<T>`). That is, once within the `ClearOnDrop`, the container is effectively immutable, like with a mutable borrow.

The dangerous ones are `&mut Box<T>`, `&mut Vec<T>`, and `&mut String`: in these cases, the "place" is the `&mut`, and the "value" is the `Box`/`Vec`/`String`, instead of their contents. That is, they're cleared by the `Default` for `Box`/`Vec`/`String`, which will free their contents without clearing them.
