### ISSUE TITLE
Using default and regular assignments doesn't guarantee overwriting everything

### ISSUE THREAD

**Issue by cesarb** [cesarb/clear_on_drop#7]
As mentioned in #3, just assigning a `Default::default()` might not overwrite everything in case the value contains an `enum` (most probably an `Option`).

Simply using `mem::zeroed` is not a good idea if the type contains something for which an all-zero-bits value is invalid.

Possible solution: convert the `&mut T` to `*mut T`, and do a `memset` to zero immediately followed by a `ptr::write` of the `Default::default()`, which is valid regardless of `dst`'s contents, since `ptr::write` ignores the target's contents (it's the official way to initialize a `mem::uninitialized()`), followed then by the `hide_mem`. The compiler should be able to elide the `memset` in the common case where just a `Default` is enough to overwrite everything.

cc #5, @burdges, @bluss

**Comment by burdges** [comment]
I'd imagine the reverted commit https://github.com/cesarb/clear_on_drop/pull/5/commits/ccb563e148f79199482af21a575e9114e451d1f0#diff-ac56d72e9f4cbe36b5de6fb90bd33456R33 solves the problem because the `ptr::write` copies from `Default::default()` without dropping the value already there, so the only drop should be the `*self = mem::zeroed::<Self>();`  I'd imagine LLVM would optimizes it to write only once, but not sure.

**Comment by cesarb** [comment]
Fixed by the `ptr::write_bytes` in commit 517686ed060de2f8ca52d08a5594d82f8e4b11c9.
